export const API_CONFIG = {
  BASE_URL: process.env.EXPO_PUBLIC_BASE_URL,
  VIA_CEP_URL: process.env.EXPO_PUBLIC_VIA_CEP_URL,
};

export const UI_SETTINGS = {
  STATUS_DURATION: 3000,
  LOAD_SIMULATION_TIME: 1000,
};